const TILE = {
  // Galaxy map tiles
  VOID:            { pass:true,  sprite:null,                drawFn:'void'     },
  NEBULA:          { pass:true,  sprite:null,                drawFn:'nebula'   },
  CASINO:          { pass:true,  sprite:null,                drawFn:'casino'   },
  PIRATE_BASE:     { pass:false, sprite:null,                drawFn:'pirate_base' },
  SYSTEM:          { pass:true,  sprite:null,                drawFn:null        },
  BASE:            { pass:true,  sprite:'starbase',          drawFn:null        },
  // Planet floor tiles
  FLOOR:           { pass:true,  sprite:'earth_floor',       drawFn:null        },
  EARTH_FLOOR:     { pass:true,  sprite:'earth_floor',       drawFn:null        },
  BLOOM_FLOOR:     { pass:true,  sprite:null,                drawFn:'bloom_floor' },
  BLOOM_FLOOR2:    { pass:true,  sprite:null,                drawFn:'bloom_floor2' },
  BLOOM_THICKET:   { pass:true,  sprite:null,                drawFn:'bloom_thicket' },
  TOXIC_FLOOR:     { pass:true,  sprite:'toxic_floor',       drawFn:null            },
  TOXIC_FLOOR2:    { pass:true,  sprite:'toxic_floor2',      drawFn:null            },
  TOXIC_FLOOR3:    { pass:true,  sprite:'toxic_floor3',      drawFn:null            },
  DESERT_FLOOR:    { pass:true,  sprite:'desert_floor',      drawFn:null        },
  FROZEN_FLOOR:    { pass:true,  sprite:'frozen_floor',      drawFn:null            },
  ASTEROID_FLOOR:  { pass:true,  sprite:'asteroid_floor',    drawFn:null        },
  VOLCANIC_FLOOR:  { pass:true,  sprite:'volcanic_floor',    drawFn:null        },
  VOLCANIC_FLOOR2:  { pass:true,  sprite:'volcanic_floor2',   drawFn:null        },
  ANCIENT_FLOOR:   { pass:true,  sprite:'ancient_floor',     drawFn:null                    },
  ANCIENT_ROAD:    { pass:true,  sprite:null,                 drawFn:'ancient_road'          },
  ANCIENT_WALL:    { pass:false, sprite:null,                 drawFn:'ancient_wall'          },
  ANCIENT_OUTPOST: { pass:true,  sprite:null,                 drawFn:'ancient_outpost_floor' },
  // Rock tiles (impassable)
  ROCK:            { pass:false, sprite:'earth_rock',        drawFn:null        },
  EARTH_ROCK:      { pass:false, sprite:'earth_rock',        drawFn:null        },
  EARTH_WATER:     { pass:true,  sprite:'earth_water',       drawFn:null        },
  EARTH_FOREST:    { pass:true,  sprite:'earth_forest',      drawFn:null        },
  NEST:            { pass:true,  sprite:'earth_floor',       drawFn:'nest'      },
  CAVE_NEST:       { pass:true,  sprite:'cave_floor',        drawFn:'cave_nest' },
  EARTH_ROCK2:     { pass:false, sprite:'earth_rock2',       drawFn:null        },
  TOXIC_ROCK:      { pass:false, sprite:'toxic_rock',        drawFn:null        },
  TOXIC_ROCK2:     { pass:false, sprite:'toxic_rock2',       drawFn:null        },
  DESERT_ROCK:     { pass:false, sprite:'desert_rock',       drawFn:null        },
  DESERT_ROCK2:    { pass:false, sprite:'desert_rock2',      drawFn:null        },
  FROZEN_ROCK:     { pass:false, sprite:'frozen_rock',       drawFn:null        },
  FROZEN_ROCK2:    { pass:false, sprite:'frozen_rock2',      drawFn:null        },
  VOLCANIC_ROCK:   { pass:false, sprite:'volcanic_rock',     drawFn:null        },
  VOLCANIC_ROCK2:  { pass:false, sprite:'volcanic_rock2',    drawFn:null        },
  ASTEROID_ROCK:   { pass:false, sprite:'asteroid_rock',     drawFn:null        },
  ASTEROID_ROCK2:  { pass:false, sprite:'asteroid_rock2',    drawFn:null        },
  ANCIENT_ROCK:    { pass:false, sprite:null,                 drawFn:'ancient_ruin'  },
  ancient_locked_door: { pass:false, sprite:null, drawFn:'ancient_locked_door', isAncientDoor:true },
  ancient_statue:  { pass:false, sprite:null, drawFn:'ancient_statue' },
  // Special
  LAVA:            { pass:true,  sprite:'lava_floor',        drawFn:null        },  // legacy alias ? LAVA_FLOOR
  LAVA_FLOOR:      { pass:true,  sprite:'lava_floor',        drawFn:null        },
  LAVA_CRUST:      { pass:true,  sprite:'lava_crust',        drawFn:null        },
  AMMONIA:         { pass:true,  sprite:'ammonia',           drawFn:null        },
  GEYSER:          { pass:true,  sprite:'geyser',            drawFn:null        },
  GEYSER_ACTIVE:   { pass:true,  sprite:'geyser_active',     drawFn:null        },
  // Items
  MINERAL:         { pass:true,  sprite:null,                drawFn:null        },
  MINERAL_SAMPLE:  { pass:true,  sprite:null,                drawFn:'mineral_sample' },
  ARTIFACT:        { pass:true,  sprite:'artifact',          drawFn:null        },
  BIODATA:         { pass:true,  sprite:'biodata',           drawFn:null        },
  // Entities drawn separately
  ALIEN:           { pass:false, sprite:'alien',             drawFn:null        },
  XALIEN:          { pass:false, sprite:'alien_boss',        drawFn:null        },
  // Procedural creature types — sprite overridden at render time from enemy.sprite
  CREATURE:        { pass:false, sprite:'creature_quadruped',drawFn:null        },
  // Ship landing pad
  SHIP:            { pass:true,  sprite:'ship_tile',         drawFn:null        },
  // Cave tiles
  CAVE_ENTRANCE:   { pass:true,  sprite:null, drawFn:'CAVE_ENTRANCE' },
  cave_floor:      { pass:true,  sprite:null, drawFn:'cave_floor'   },
  cave_wall:       { pass:false, sprite:null, drawFn:'cave_wall'    },
  cave_stalagtite: { pass:false, sprite:null, drawFn:'cave_stalagtite' },
  cave_exit:       { pass:true,  sprite:null, drawFn:'cave_exit'    },
  // Underwater tiles
  uw_floor:        { pass:true,  sprite:null, drawFn:'uw_floor'     },
  uw_wall:         { pass:false, sprite:null, drawFn:'uw_wall'      },
  uw_kelp:         { pass:true,  sprite:null, drawFn:'uw_kelp'      },
  uw_coral:        { pass:true,  sprite:null, drawFn:'uw_coral'     },
  uw_vent:         { pass:false, sprite:null, drawFn:'uw_vent'      },
  uw_wreck:        { pass:true,  sprite:null, drawFn:'uw_wreck'     },
  uw_exit:         { pass:true,  sprite:null, drawFn:'uw_exit'      },
  // Derelict station tiles
  station_floor:   { pass:true,  sprite:null, drawFn:'station_floor'   },
  station_crack:   { pass:true,  sprite:null, drawFn:'station_crack'   },
  station_wall:    { pass:false, sprite:null, drawFn:'station_wall'    },
  station_door:    { pass:true,  sprite:null, drawFn:'station_door'    },
  station_console: { pass:true,  sprite:null, drawFn:'station_console' },
  station_locker:  { pass:true,  sprite:null, drawFn:'station_locker'  },
  station_corpse:  { pass:true,  sprite:null, drawFn:'station_corpse'  },
  // Ancient station tiles
  ancient_st_floor:  { pass:true,  sprite:null, drawFn:'ancient_st_floor'  },
  ancient_st_edge:   { pass:true,  sprite:null, drawFn:'ancient_st_edge'   },
  ancient_st_corner: { pass:true,  sprite:null, drawFn:'ancient_st_corner' },
  ancient_st_node:   { pass:true,  sprite:null, drawFn:'ancient_st_node'   },
  ancient_st_fuel:   { pass:true,  sprite:null, drawFn:'ancient_st_fuel'   },
  ancient_st_trap:   { pass:true,  sprite:null, drawFn:'ancient_st_trap'   },
  ancient_st_void:   { pass:true,  sprite:null, drawFn:null                }, // handled inline (animated void)
  ancient_st_glow:   { pass:true,  sprite:null, drawFn:'ancient_st_glow'   },
  // Ringworld tiles
  rw_floor:          { pass:true,  sprite:null, drawFn:'rw_floor'          },
  rw_debris:         { pass:true,  sprite:null, drawFn:'rw_debris'         },
  rw_wall:           { pass:false, sprite:null, drawFn:'rw_wall'           },
  rw_locked_door:    { pass:false, sprite:null, drawFn:'rw_locked_door'    },
  rw_open_door:      { pass:true,  sprite:null, drawFn:'rw_open_door'      },
  rw_console:        { pass:true,  sprite:null, drawFn:'rw_console'        },
  rw_void:           { pass:true,  sprite:null, drawFn:null                }, // lethal void — handled inline
  // Nuclear War Planet tiles
  nuke_dirt:       { pass:true,  sprite:null, drawFn:'nuke_dirt'      },
  nuke_rock:       { pass:false, sprite:null, drawFn:'nuke_rock'      },
  nuke_water:      { pass:true,  sprite:null, drawFn:'nuke_water'     },
  nuke_dead_tree:  { pass:false, sprite:null, drawFn:'nuke_dead_tree' },
  nuke_crater:     { pass:true,  sprite:null, drawFn:'nuke_crater'    },
  nuke_ruin:       { pass:false, sprite:null, drawFn:'nuke_ruin'      },
  nuke_ruin2:      { pass:false, sprite:null, drawFn:'nuke_ruin2'     },
  // -- Civilization structure tiles (all passable — interaction placeholder) --
  civ_hut:           { pass:true,  sprite:null, drawFn:'civ_hut'           },
  civ_fire_pit:      { pass:true,  sprite:null, drawFn:'civ_fire_pit'      },
  civ_longhouse:     { pass:true,  sprite:null, drawFn:'civ_longhouse'     },
  civ_totem:         { pass:true,  sprite:null, drawFn:'civ_totem'         },
  civ_stone_tower:   { pass:true,  sprite:null, drawFn:'civ_stone_tower'   },
  civ_market:        { pass:true,  sprite:null, drawFn:'civ_market'        },
  civ_factory:       { pass:true,  sprite:null, drawFn:'civ_factory'       },
  civ_tenement:      { pass:true,  sprite:null, drawFn:'civ_tenement'      },
  civ_office:        { pass:true,  sprite:null, drawFn:'civ_office'        },
  civ_relay_tower:   { pass:true,  sprite:null, drawFn:'civ_relay_tower'   },
  uw_civ_shelter:    { pass:true,  sprite:null, drawFn:'uw_civ_shelter'    },
  uw_civ_reef_totem: { pass:true,  sprite:null, drawFn:'uw_civ_reef_totem' },
  uw_civ_habitat:    { pass:true,  sprite:null, drawFn:'uw_civ_habitat'    },
  uw_civ_bastion:    { pass:true,  sprite:null, drawFn:'uw_civ_bastion'    },
  uw_civ_exchange:   { pass:true,  sprite:null, drawFn:'uw_civ_exchange'   },
  uw_civ_processor:  { pass:true,  sprite:null, drawFn:'uw_civ_processor'  },
  uw_civ_pod_stack:  { pass:true,  sprite:null, drawFn:'uw_civ_pod_stack'  },
  uw_civ_archive:    { pass:true,  sprite:null, drawFn:'uw_civ_archive'    },
  uw_civ_sonar:      { pass:true,  sprite:null, drawFn:'uw_civ_sonar'      },
  civ_ruin:          { pass:true,  sprite:null, drawFn:'nuke_ruin'         },
};
// -- Game state ---------------------------------------------------
